KOD-8.3: RouteNotFoundException
mwiski/Mateusz-Wiski-kodilla-java pull request #14
Opened 2019-04-27 09:53 UTC by mwiski

2019-04-27 10:01 UTC, mwiski commented
Wyjaśnienie: to zadanie jest trochę dziwne. Miałem stworzyć klasę Flight, w której konstruktorze dać argumenty departureAirport i arrivalAirport. Natomiast w klasie zawierającej logikę imitującą wyszukiwanie lotów stworzyć metodę findFilght(Flight flight). "Wewnątrz metody zaimplementuj mapę typu HashMap, której kluczem będzie String przechowujący nazwę lotniska, a wartością Boolean informujący o tym czy można na dane lotnisko polecieć. Przykład: Map<String, Boolean>. c) logika powinna wyszukiwać loty w mapie. Jeżeli dane lotnisko nie będzie istnieć w mapie, należy rzucić wyjątkiem RouteNotFoundException."

W sumie to to trochę nie ma sensu. W metodzie wpisuję już konkretny lot, a wyszukuję lotniska docelowego i czy można tam dolecieć. Powinienem chyba jako argumenty metody podawać nazwę lotniska, z którego się wylatuje i nazwę lotniska docelowego, a metoda wyszukiwałaby, czy taki lot istnieje. Bo co mi z tego, że będę szukał np. lotu z Warszawy do Wrocławia, a metoda mi pokazuje, że: to prawda, można dolecieć na lotnisko do Wrocławia. Tylko, że nie wiem dalej czy można na nie dolecieć z Warszawy. 

Bądź co bądź, zrobiłem to tak, że wpisuje się do metody lot, a metoda wyszukuje czy można dolecieć na dane lotnisko i zwraca wartość Value z HashMap'y, true lub false czy można tam dolecieć. Zakładałem, że ktoś wyszukuje lotów z jednego lotniska np. Warszawy na jakieś inne lotniska. Wtedy to ma trochę sensu.

2019-04-30 20:33 UTC, mps4dev requested changes
Generalnie bardzo ładnie, drobne zmiany tylko wedlug mnie

2019-04-30 20:33 UTC, mps4dev commented on kodilla-exception/src/main/java/com/kodilla/exception/test/FlightsProcessor.java
> +        for (Map.Entry<String, Boolean> entry : airports.entrySet()) {
Postaraj się to zapisać bardziej elegancko - za pomocą stream api :)

2019-04-30 20:33 UTC, mps4dev commented on kodilla-exception/src/main/java/com/kodilla/exception/test/FlightsProcessor.java
> +        throw new RouteNotFoundException();
dobrze jest podać message w konstruktorze, np. `throw new RouteNotFoundException("Route to " + flight.getArrivalPort() + " not found");`

2019-04-30 20:33 UTC, mps4dev commented on kodilla-exception/src/main/java/com/kodilla/exception/test/RouteNotFoundException.java
> +public class RouteNotFoundException extends Exception{
spacja przed "{"
Ponadto dodać konstruktor `public RouteNotFoundException(String message) { super(message); }`

2019-05-02 09:51 UTC, mps4dev approved these changes
:+1:

2019-05-02 10:04 UTC, merged