KOD-13.4: flights challenge
mwiski/Mateusz-Wiski-kodilla-java pull request #18
Opened 2019-06-02 11:40 UTC by mwiski

2019-06-03 05:55 UTC, mps4dev approved these changes
:-1:

2019-06-03 05:55 UTC, mps4dev commented on kodilla-good-patterns/src/main/java/com/kodilla/good/patterns/flights/CityType.java
> +public enum CityType {
Nazwa CityType wskazywałaby na rodzaj miast, a tu mamy poprostu miasto. Może poprostu użyć nazwy City? Albo zrobić listę stringów z nazwami miast.

2019-06-03 05:55 UTC, mps4dev commented on kodilla-good-patterns/src/main/java/com/kodilla/good/patterns/flights/Flight.java
> +    private final CityType through;
Myślę, że to pole jest zbędne. Loty są zazwyczaj z punktu A do punktu B.

2019-06-03 05:55 UTC, mps4dev commented on kodilla-good-patterns/src/main/java/com/kodilla/good/patterns/flights/FlightsProcessor.java
> +    public String findFlightThrough(CityType from, CityType to, CityType through) {
To jest takie nierealne. W zadaniu jest "znalezienie lotow przez inne miasto". Moim zdaniem metoda powinna mieć jeden parametr :) City through (chyba raczej via)

2019-06-03 21:15 UTC, mps4dev requested changes
Moim zdaniem to nadal nie jest to :) Według zadania mamy dla lotu tylko miasto wylotu i miasto przylotu :) Nie ma czegoś takiego jak miasto pośrednie :D Lot jest "z" "do", czyli klasa Flight ma tylko dwa pola: `from` oraz `to`. Wtedy implementacja metody znajdującej właśnie loty z przesiadką staje się wyzwaniem :)

2019-06-04 08:18 UTC, mwiski commented
Ok, właśnie tak też myślałem, ale nie byłem pewien czy o to chodzi ;) . Tzn. powinienem zrobić tak, że jeśli nie ma połączenia bezpośredniego załóżmy z Warszawy do Londynu, to metoda powinna znaleźć połączenia z Warszawy do miasta X, z którego można polecieć do Londynu i wtedy załóżmy zwraca String "Flight Warszawa - X, X - Londyn". Coś takiego

2019-06-05 07:58 UTC, mps4dev requested changes
:-1: 
Popraw formatowanie, zaś rozwiązanie teraz jest jak najbardziej okej :)

2019-06-05 07:58 UTC, mps4dev commented on kodilla-good-patterns/src/main/java/com/kodilla/good/patterns/flights/FlightsProcessor.java
> +                .filter(city -> flights.stream().filter(flight -> flight.getTo() == to).map(Flight::getFrom).anyMatch(city1 -> city1 == city))
bardzo nieładnie sformatowane :)

2019-06-05 16:09 UTC, mps4dev approved these changes
:+1:

2019-06-05 16:58 UTC, merged