Rock-Paper-Scissors first classes
mwiski/Mateusz-Wiski-kodilla-java pull request #38
Opened 2019-07-18 20:23 UTC by mwiski

2019-07-18 20:25 UTC, mwiski commented
Stworzyłem projekt i kilka pierwszych klas, aby zacząć. Wiem, że mówiłeś, żeby zrobić ruch komputera jako enum, ale chciałem mieć enum ze znakami(papier, kamień, nożyce). Chyba, że mam to zmienić - i wtedy dodać metodę ruchu komputera w enumie?

2019-07-19 05:46 UTC, mps4dev requested changes
Zmiany z enumem glownie. Interfejs Shapes niepotrzebnyjest.

2019-07-19 05:46 UTC, mps4dev commented on kodilla-rps/src/main/java/com/kodilla/rps/shapes/Shapes.java
> +public interface Shapes {
Ten interfejs niepotrzebny jest. Enum maetodw zwracajaca liste wszystkich jego elementow.

2019-07-19 05:46 UTC, mps4dev commented on kodilla-rps/src/main/java/com/kodilla/rps/strategy/ComputerStrategy.java
> +    private Random random = new Random();
Static

2019-07-19 05:46 UTC, mps4dev commented on kodilla-rps/src/main/java/com/kodilla/rps/strategy/ComputerStrategy.java
> +        return Shapes.SHAPES.get(random.nextInt(3));
Enum ma mozliwosc odwolania sie po liczbie kardynalbej doswoich elementow.

2019-07-21 15:34 UTC, mps4dev requested changes
Wydziel klase i jej obiekt do przechowyeania stanu gry (ststystyk).

2019-07-21 15:34 UTC, mps4dev commented on kodilla-rps/src/main/java/com/kodilla/rps/strategy/Strategy.java
> +
To jest naprawde Strategy?

2019-07-21 15:34 UTC, mps4dev commented on kodilla-rps/src/main/java/com/kodilla/rps/strategy/Strategy.java
> +
Jesli tak, to po co tu sa statystyki?

2019-07-24 18:51 UTC, mps4dev requested changes
:-1:

2019-07-24 18:51 UTC, mps4dev commented on kodilla-rps/src/main/java/com/kodilla/rps/RpsRunner.java
> +
Zwyczajowo główną klasę, od ktorej zaczynamy, nazywa się `*Application` (łatwo wtedy komuś, kto nie zna kodu, znaleźć klasę, od ktorej się wszystko zaczyna) :) A więc proponuję `RpsApplication` :)

2019-07-24 18:51 UTC, mps4dev commented on kodilla-rps/src/main/java/com/kodilla/rps/RpsRunner.java
> +        game.init();
Jak dla mnie, to główna klasa nic nie musi wiedzieć, że jest jakiś init :) Lepiej zrobić tutaj tylko jedną linijkę: `new Game().run(); i tyle w temacie. Klasa Game sama musi się zatroszczyć o inicjalizację (delegacja - pamiętasz?)

2019-07-24 18:51 UTC, mps4dev commented on kodilla-rps/src/main/java/com/kodilla/rps/engine/Game.java
> +    private Round round;
to raczej będzie zmienną lokalną, a nie polem klasy. Ale za to tutaj powinno być `private GameStatistics statistics;`

2019-07-24 18:51 UTC, mps4dev commented on kodilla-rps/src/main/java/com/kodilla/rps/gameDefinition/GameDefinition.java
> +    public void setUserName(String userName) {
settery są nam niepotrzebne - klasa powinna być Immutable (nic się przecież w danej grze nie zmieni tutaj)

2019-07-24 18:51 UTC, mps4dev commented on kodilla-rps/src/main/java/com/kodilla/rps/gameDefinition/GameDefinition.java
> +    public void setUserName(String userName) {
Inicjalizujemy w konstruktorze, albo dostarczamy metodę fabrykującą.

2019-07-24 18:51 UTC, mps4dev commented on kodilla-rps/src/main/java/com/kodilla/rps/gui/UserInterface.java
> +    private static Scanner scanner;
`final`

2019-07-24 18:51 UTC, mps4dev commented on kodilla-rps/src/main/java/com/kodilla/rps/model/Shape.java
>  public enum Shape {
`Shape` to trochę zla nazwa. Nazwałbym `Move`

2019-07-24 18:51 UTC, mps4dev commented on kodilla-rps/src/main/java/com/kodilla/rps/round/Round.java
> +    private RoundChecker checker;
tutaj też powinna dostać statystyki i definicję w konstruktorze, zaś RoundChecker może być `final`

2019-07-24 18:51 UTC, mps4dev commented on kodilla-rps/src/main/java/com/kodilla/rps/round/Round.java
> +    public Round(RoundChecker checker) {
nie jako parametr i nie w konstruktorze. Poprostu `checker = new RoundChecker();`

2019-07-24 18:51 UTC, mps4dev commented on kodilla-rps/src/main/java/com/kodilla/rps/round/Round.java
> +    public void move() {
raczej `play()` albo `start()`

2019-07-24 18:51 UTC, mps4dev commented on kodilla-rps/src/main/java/com/kodilla/rps/round/RoundChecker.java
> +    private Shape compare(Shape userShape, Shape computerShape) {
`playerMove` oraz `computerMove`

2019-07-24 18:51 UTC, mps4dev commented on kodilla-rps/src/main/java/com/kodilla/rps/round/RoundChecker.java
> +            return null;
null ?

2019-07-24 18:51 UTC, mps4dev commented on kodilla-rps/src/main/java/com/kodilla/rps/round/RoundChecker.java
> +    private Shape compare(Shape userShape, Shape computerShape) {
Metoda nie może zwracać Shape. Moim zdaniem trzeba wprowadzić enum `RoundResult` i to tutaj zwrócić.

2019-07-24 18:51 UTC, mps4dev commented on kodilla-rps/src/main/java/com/kodilla/rps/round/RoundChecker.java
> +    private Shape compare(Shape userShape, Shape computerShape) {
Metoda ma otrzymać ruch playera oraz komputera i zwrócić jaki jest rezultat. 
Rezultat może być: PLAYER, COMPUTER, DRAW, END, EXIT :)

2019-07-24 18:51 UTC, mps4dev commented on kodilla-rps/src/main/java/com/kodilla/rps/statistics/RoundResult.java
> +    WIN,
Ma mówić o tym, kto wygrał. Może być też WIN (że player wygral rundę), LOSE (że player przegral, czyli komputer wygrał), DRAW (remis) oraz brakuje rezultatu dla klawiszy 'x' oraz 'n' czyli EXIT oraz END.

2019-07-24 18:51 UTC, mps4dev commented on kodilla-rps/src/main/java/com/kodilla/rps/statistics/Statistics.java
> +    private int userRoundResult;
po co te dwa pierwsze pola? Ja bym poprostu dal:
`private int roundNumber; // numer aktualnej rundy (wiemy więc, ile rund już bylo rozegranych)`
`private int wins; // ile razy Player wygrał`
`private int losts // ile razy player przegrał, a więc komputer wygrał`
Uwaga: jeśli w enumie masz WIN, LOSE - to tutaj zrób analogicznie wins, losts; Jeśli w enumie zrobisz PLAYER, COMPUTER - to tutaj plaerWins, computerWins :) Bądźmy konsekwentni

2019-07-24 18:51 UTC, mps4dev commented on kodilla-rps/src/main/java/com/kodilla/rps/strategy/ComputerStrategy.java
> +    public Shape getShape() {
getMove()

2019-07-24 18:51 UTC, mps4dev commented on kodilla-rps/src/main/java/com/kodilla/rps/strategy/ComputerStrategy.java
> +public class ComputerStrategy {
Proponuję wprowadzić interfejs Stratey
`public interface Strategy { Move getMove(); }` i obie klasy ComputerStrategy oraz Player strategy niech go implementują.

2019-07-27 18:45 UTC, mwiski commented
Gra działa, ale zawiera bugi. Na razie zapisuję w takiej wersji, ale wiem, że do poprawy.

2019-07-28 16:03 UTC, mps4dev requested changes
Podeślę ci mój schemat gry, to sobie porównasz :)

2019-07-28 16:03 UTC, mps4dev commented on kodilla-rps/src/main/java/com/kodilla/rps/RpsRunner.java
> +        new RpsApplication();
głowna klasa miała być RpsApplication, a nie RpsRunner. Klasa RpsRunner nam się przyda do tego, aby uruchamiać kolejne gry.

2019-07-28 16:03 UTC, mps4dev commented on kodilla-rps/src/main/java/com/kodilla/rps/engine/RpsApplication.java
> +    private static PlayerStrategy playerStrategy;
czemu tylko strategia playera jest wstrzyknięta?

2019-07-28 16:03 UTC, mps4dev commented on kodilla-rps/src/main/java/com/kodilla/rps/gui/UserInterface.java
> +    private final static Scanner scanner = new Scanner(System.in);
dodaj jeszcze interfejs UserInterface, a tę klase nazwij np. SimpleUserInterface implements UserInterface.

2019-07-29 17:29 UTC, mwiski commented
Widziałem Twój "szkielet" i rzeczywiście stwierdzam, że byłby to bardziej przejrzysty widok w klasach :) . Pozmieniałem trochę u mnie, ale już  brnąłem w "swój" projekt. Właśnie tworząc "dalsze" klasy zaczynałem iść pod górkę i zamiast je rozbijać to dawałem im wszytko do zrobienia. Bo ciągle gdzieś miałem taką obawę z tyłu głowy, czy za bardzo nie rozbiję klas. W ogóle w pewnym momencie postanowiłem zapisać sobie na kartce, co chciałbym, aby po kolei działo się w mojej grze - i wtedy jak spojrzałem na to z dalszej perspektywy to dopiero zacząłem rozumieć czego będę potrzebował.

2019-07-30 14:02 UTC, mps4dev requested changes
:-1:

2019-07-30 14:02 UTC, mps4dev commented on kodilla-rps/src/main/java/com/kodilla/rps/RpsApplication.java
> +        GameRunner gr = new GameRunner(new SimpleUserInterface());
zmienną nazwij gameRunnr poprostu

2019-07-30 14:02 UTC, mps4dev commented on kodilla-rps/src/main/java/com/kodilla/rps/engine/Game.java
> +        gui.printIntro();
a po co tu zdradzać, że jest jakieś printIntro? Czy nie może zrobić tego metoda w UserInterfejsie?

2019-07-30 14:02 UTC, mps4dev commented on kodilla-rps/src/main/java/com/kodilla/rps/round/AfterRound.java
> +    public void react(UserInterface gui, RoundResult result, Round round, Statistics statistics) {
Dlaczego tu jest rzekazywany GUI? Coś nie tak

2019-07-30 14:02 UTC, mps4dev commented on kodilla-rps/src/main/java/com/kodilla/rps/round/Round.java
> +    public RoundResult play(AfterRound afterRound) {
Czemu ta mtoda ma parametr?

2019-08-04 10:34 UTC, mps4dev requested changes
Już prawie kończymy :) Drobne uwagi tylko.

2019-08-04 10:34 UTC, mps4dev commented on kodilla-rps/src/main/java/com/kodilla/rps/statistics/Statistics.java
> +        playerRoundsWin = 0;
tej metody nie używasz w ogóle - do usunięcia

2019-08-04 10:34 UTC, mps4dev commented on kodilla-rps/src/main/java/com/kodilla/rps/strategy/ComputerStrategy.java
> +    private static final List<Move> COMPUTER_MOVES = Arrays.asList(Move.ROCK, Move.PAPER, Move.SCISSORS);
Nie używasz metody z klasy Move. Użyj tamtej metody, po co komplikować? Poprostu `Move.get(random.nextInt(3));`

2019-08-04 13:21 UTC, mwiski commented on kodilla-rps/src/main/java/com/kodilla/rps/strategy/ComputerStrategy.java
> +    private static final List<Move> COMPUTER_MOVES = Arrays.asList(Move.ROCK, Move.PAPER, Move.SCISSORS);
Ok. Dałem listę z dostępnymi ruchami komputera, bo obawiałem się, że może wystąpić później jakiś błąd, gdyby komputer wylosował EXIT albo RESET.

2019-08-04 13:47 UTC, mps4dev approved these changes
Ok. ladnie :) 👍

2019-08-04 14:30 UTC, merged