KOD-Sudoku: first draft
mwiski/Mateusz-Wiski-kodilla-java pull request #39
Opened 2019-08-09 22:02 UTC by mwiski

2019-08-12 06:38 UTC, mps4dev requested changes
:-1:

2019-08-12 06:38 UTC, mps4dev commented on kodilla-sudoku/src/main/java/com/kodilla/sudoku/board/creator/BoardCreator.java
>      public void createBoard(int boardSize, int blockSize) {
przedziwne ... jak coś ma zrobić create, to musi to co stworzyło zwrócić. Wpp. nie jest kreatorem :/

2019-08-12 06:38 UTC, mps4dev commented on kodilla-sudoku/src/main/java/com/kodilla/sudoku/board/creator/BoardCreator.java
>      public void createBoard(int boardSize, int blockSize) {
Dlaczego w konstruktorze kreator dostaje coś, co ma stworzyć?

2019-08-12 06:38 UTC, mps4dev commented on kodilla-sudoku/src/main/java/com/kodilla/sudoku/engine/SudokuGame.java
>      private final static SudokuElement RESOLVE_SUDOKU = new SudokuElement(-1, -1);
co to za dzwiny twor?

2019-08-12 06:38 UTC, mps4dev commented on kodilla-sudoku/src/main/java/com/kodilla/sudoku/engine/SudokuGame.java
> +    private static Random random = new Random();
final

2019-08-12 06:38 UTC, mps4dev commented on kodilla-sudoku/src/main/java/com/kodilla/sudoku/userinterface/UserInterface.java
> +
Nie wszystkie metody, ktore będą zaimplementowane w klasie, muszą się znaleźć w interfejsie. Np. metoda validate może być metodą prywatną w klasie.

2019-08-12 06:38 UTC, mps4dev commented on kodilla-sudoku/src/main/java/com/kodilla/sudoku/validator/SudokuValidator.java
>      public boolean validate(SudokuElement element) {
Ta metoda nie waliduje przecież. Czy to w ogóle jest walidator? Może lepiej nazwać tę klasę checker?

2019-08-13 09:29 UTC, mps4dev requested changes
Nie widzę nadal poprawek do poprzednio zgłoszonych uwag

2019-08-13 09:29 UTC, mps4dev commented on kodilla-sudoku/src/main/java/com/kodilla/sudoku/checker/SudokuChecker.java
> +        if (!checkRow(element)) {
pomyśl nad lepszymi nazwami. Metoda check() mówi, że ma coś sprawdzić ... i co? Co oznacza wynik true? Że sprawdziło?

2019-08-13 09:29 UTC, mps4dev commented on kodilla-sudoku/src/main/java/com/kodilla/sudoku/engine/SudokuGame.java
> +                        element.setValue(element.getValue());
na pewno tak? dla mnie to wywolanie nic nie zmienia: value jest ustawiane na dotychczasowe value

2019-08-13 09:29 UTC, mps4dev commented on kodilla-sudoku/src/main/java/com/kodilla/sudoku/userinterface/SimpleUserInterface.java
> +        return (playerMove.matches("\\d" + "," + "\\d" + "," + "\\d") || playerMove.equals("SUDOKU"))
użyj innego regexu: `playerMove.matches("([1-9],[1-9],[1-9]|SUDOKU)")`

2019-08-15 22:25 UTC, mps4dev requested changes
Jest w miarę okej. 
Sprobuj swoj kod przeczytać "po polsku/po angielsku" i wytłumaczyć "gumowej kaczuszce" co się dzieje w kodzie krok po kroku.

2019-08-15 22:25 UTC, mps4dev commented on kodilla-sudoku/src/main/java/com/kodilla/sudoku/checker/SudokuChecker.java
> +import com.kodilla.sudoku.board.*;
staraj się nie używać wildcartów (*)

2019-08-15 22:25 UTC, mps4dev commented on kodilla-sudoku/src/main/java/com/kodilla/sudoku/checker/SudokuChecker.java
> +    private boolean checkIfCanBeAddedToRow(SudokuElement element) {
nazwa matody zaczynająca się od check malo mówi :) lepiej nazwać `isElementEmpty` czy `canBe AddedToRow`

2019-08-15 22:25 UTC, mps4dev commented on kodilla-sudoku/src/main/java/com/kodilla/sudoku/engine/SudokuGame.java
> +    private static final int BLOCK_SIZE = 3;
wprowadziłbym jąś zależność, np. `BOARD_SIZE = BLOCK_SIZE * BLOCK_SIZE;`

2019-08-15 22:25 UTC, mps4dev commented on kodilla-sudoku/src/main/java/com/kodilla/sudoku/engine/SudokuGame.java
> +        while (!(playerMove = userInterface.getPlayerMove()).equals("SUDOKU")) {
unikaj takich konstrukcji w warunku pętli: tu mamy przypisanie i porównanie i dodatkowo jeszcze z negacja. 
wprowadź metodę np. `shouldResolve(playerMove)` i `while(!shouldResolve(playerMove)) { ... }`

2019-08-15 22:25 UTC, mps4dev commented on kodilla-sudoku/src/main/java/com/kodilla/sudoku/engine/SudokuGame.java
> +                    newElement.setValue(random.nextInt(BOARD_SIZE) + 1);
Wprowadź metodę `private int getRandomMove() { return random.nextInt(BOARD_SIZE) + 1;}`

2019-08-15 22:25 UTC, mps4dev commented on kodilla-sudoku/src/main/java/com/kodilla/sudoku/engine/SudokuRunner.java
> +            if (!theGame.play()) {
Dziwnie się czyta ten warunek: "dopóki nie graj gry ... " ? Może wprowadzić jakąś zmienną o nazwie `shouldPlay`?

2019-08-19 21:15 UTC, mwiski commented
Gra działa. Mogą być jakieś małe błędy - w sensie literówki. Ale o północy zamyka mi się dostęp do modułów, więc chciałem dosłać jeszcze dzisiaj działającą grę

2019-08-20 09:02 UTC, mps4dev approved these changes
Zamiast zer na planszy wyświetlaj puste miejsca albo kropki :)

2019-08-20 20:10 UTC, merged