KOD-30.5: sql event using view
mwiski/Mateusz-Wiski-kodilla-java pull request #49
Opened 2019-10-28 16:44 UTC by mwiski

2019-10-29 10:15 UTC, mps4dev requested changes
:-1:

2019-10-29 10:15 UTC, mps4dev commented on SQL statements/eventUsingView.sql
> +SELECT COUNT(*) AS BESTSELLERS_COUNT FROM BOOKS WHERE BESTSELLER = 1;
a gdzie jest widok?

2019-10-29 10:24 UTC, mwiski commented on SQL statements/eventUsingView.sql
> +SELECT COUNT(*) AS BESTSELLERS_COUNT FROM BOOKS WHERE BESTSELLER = 1;
No jest create view bestsellers_count

2019-10-31 08:14 UTC, mps4dev approved these changes
👍

2019-10-31 18:11 UTC, merged