KOD-6.5: StatisticsCollector
mwiski/Mateusz-Wiski-kodilla-java pull request #5
Opened 2019-04-13 14:59 UTC by mwiski

2019-04-14 21:15 UTC, mps4dev requested changes
:-1:

2019-04-14 21:15 UTC, mps4dev commented on kodilla-testing/src/main/java/com/kodilla/testing/forum/statistics/StatisticsCollector.java
> +    private List<String> usersNames;
Czy potrzebujesz tego jako pól klasy?

2019-04-14 21:15 UTC, mps4dev commented on kodilla-testing/src/main/java/com/kodilla/testing/forum/statistics/StatisticsCollector.java
> +        if (usersQuantity > 0) {
a co jak jest zero?

2019-04-14 21:15 UTC, mps4dev commented on kodilla-testing/src/main/java/com/kodilla/testing/forum/statistics/StatisticsCollector.java
> +        return "There is " + usersQuantity + " users in our forum.\n"
Zbyt skomplikowana treść metody toString. Zazwyczaj chcemy to mieć w jak najbardziej zwięzły sposób. Np. {users: 10, posts: 100, comments: 40, ... } itp itd. A tak w ogóle, to po co to? Raczej dla klas utilsowych nie piszemy metod toString.

2019-04-15 13:42 UTC, mwiski commented on kodilla-testing/src/main/java/com/kodilla/testing/forum/statistics/StatisticsCollector.java
> +    private List<String> usersNames;
Potrzebuję, bo w zadaniu jest napisane, aby przypisać wartości do pól klasy.

2019-04-15 20:22 UTC, mps4dev requested changes
:-1:

2019-04-15 20:22 UTC, mps4dev commented on kodilla-testing/src/main/java/com/kodilla/testing/forum/statistics/StatisticsCollector.java
> +            avgQuantityPostsOnUser = Double.NaN;
ja bym zwracał jednak zero :) tak intuicyjnie to czuję :) wiem, że wcześniej w zadaniu zwracaliśmy NaN. Z NaN jest problem w Javie 11, ponieważ tam nie ma już takiego czegoś. 
No i po co ci pola klasy? Pola klasy mówią o jakiejś własności obiektu/klasy. Tutaj dostajemy obiekt Statistics i za jego pomocą obliczamy odpowiednie dane. Na przykład return statistics.postsCount() / usersNumber() (jeśli usersNumber() != 0) w przypadku średniej ilości postów na użytkownika itp. usersNumber() to poprostu statistics.size() ...

2019-04-16 12:05 UTC, mps4dev approved these changes
:-1:

2019-04-16 12:05 UTC, mps4dev commented on kodilla-testing/src/main/java/com/kodilla/testing/forum/statistics/StatisticsProcessor.java
> +        StatisticsCollector collector = new StatisticsCollector(0, 0, 0, 0, 0, 0);
to niepotrzebne, Java sama zainicjalizuje wartości na zero. Dopisz poprostu bezparametrowy konstruktor.

2019-04-16 17:29 UTC, mps4dev approved these changes
Nazwy nie zmieniłeś 😳
👍

2019-04-16 17:32 UTC, merged